version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.10
        environment:
          PGUSER: circletest
          PGDATABASE: circletest
          PGHOST: 127.0.0.1
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: circletest
          POSTGRES_DB: circletest
          POSTGRES_PASSWORD: ""

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: sleep 2 && yarn test
